name: bioread
dependencies:
- pytorch::pytorch
- tensorflow-gpu>=2.0.0
- tensorboard
- numpy
- nltk
- tqdm
- more-itertools
- pip
- pip:
  - gensim
  - git+https://github.com/huggingface/transformers.git
